name: Deploy backend

steps:
  - name: Install SSH Key
    uses: shimataro/ssh-key-action@v2
    with:
      key: ${{ secrets.SSH_PRIVATE_KEY }} 
      known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

  - name: Adding Known Hosts
    run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

  - name: Deploy
    run : ssh vu@${{ secrets.SSH_HOST }} "cd backend && docker-compose pull && docker-compose up -d"